-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 14:59:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_reaprender
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_reaprender
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_reaprender` DEFAULT CHARACTER SET utf8 ;
USE `db_reaprender` ;

-- -----------------------------------------------------
-- Table `db_reaprender`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reaprender`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_livro` VARCHAR(255) NOT NULL,
  `genero` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reaprender`.`tb_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reaprender`.`tb_livros` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `ano_lancamento` INT NULL,
  `editora` VARCHAR(255) NULL,
  `id_categoria` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_livros_tb_categorias_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_livros_tb_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_reaprender`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reaprender`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reaprender`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(1000) NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
